### ISSUE TITLE
Comments: How Facebook Avoid- Ad Blocker-

### ISSUE THREAD

**Issue by ganderzz** [ganderzz/dylanpaulus.com#24]
https://www.dylanpaulus.com/2019-11-24-how-fb-avoids-adblockers/

Comments for How Facebook Avoid- Ad Blocker-

**Comment by jameshilliard** [comment]
You can break the obfuscation with a filtering algorithm such as [this](https://github.com/gorhill/uBlock/compare/master...jameshilliard:has-visible-text).
